### ISSUE TITLE
在哪里可以修改文件上传的大小限制

### ISSUE THREAD

**Issue by rsa-sha2** [qunarcorp/or_open#1]
openresty在哪里配置上传文件的大小限制呢

**Comment by memacs** [comment]
可以通过修改[client_max_body_size](https://github.com/qunarcorp/or_open/blob/master/conf/nginx.conf#L40)来修改大小限制，安装路径下的文件是：/startalk/openresty/nginx/conf/nginx.conf

**Comment by memacs** [comment]
修改后通过：
/startalk/openresty/nginx/sbin/nginx -s reload

重新加载下配置
